jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'ubuntu-latest'
  environment:
    name: linux-vm-environment
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: sudo apt-get update
        - script: sudo apt-get upgrade