jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'ubuntu-latest'
  environment:
    name: linu-vm-environment
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: apt-get update